/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package leis.de.mendel;

import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author marco
 */
public class Calcular extends javax.swing.JFrame {

    /**
     * Creates new form Calcular
     */
    private Conexao mdbc;
    private java.sql.Statement stmt;
    public Calcular() throws SQLException {
        mdbc = new Conexao();
        mdbc.getConnection();
        Connection conn = mdbc.getConnection();
        stmt= conn.createStatement();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jRPrimeira = new javax.swing.JRadioButton();
        jRSegunda = new javax.swing.JRadioButton();
        jTCampo1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTCampo2 = new javax.swing.JTextField();
        jBCalcular = new javax.swing.JButton();
        jLResultado = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jBSalvar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Impact", 1, 24)); // NOI18N
        jLabel1.setText("Descubra os Genótipos!");

        jRPrimeira.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jRPrimeira.setText("1° Lei de Mendel");

        jRSegunda.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jRSegunda.setText("2° Lei de Mendel");
        jRSegunda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRSegundaActionPerformed(evt);
            }
        });

        jTCampo1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel2.setText("X");

        jTCampo2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jBCalcular.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jBCalcular.setText("Calcular");
        jBCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCalcularActionPerformed(evt);
            }
        });

        jLResultado.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLResultado.setText("Reultado");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Observações");

        jBSalvar.setText("Salvar");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(jLabel2)
                                .addGap(35, 35, 35)
                                .addComponent(jTCampo2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRPrimeira)
                                .addGap(30, 30, 30)
                                .addComponent(jRSegunda))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jBCalcular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(jBSalvar)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRPrimeira)
                    .addComponent(jRSegunda))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTCampo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jBCalcular)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBSalvar)
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRSegundaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRSegundaActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"É permitido colocar no máximo 3 pares de alelos");
    }//GEN-LAST:event_jRSegundaActionPerformed

    private void jBCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCalcularActionPerformed
        // TODO add your handling code here:
        String campo1 = jTCampo1.getText();
        String campo2 = jTCampo2.getText();
        String[] vetor1 = campo1.split("");
        String[] vetor2 = campo2.split("") ;
        
        //Executara o cálculo se a primeira lei estiver marcada      
        if(jRPrimeira.isSelected()){
            //String[,] array = new String[4,4];
            //Dados vetor 1
            String p1 = vetor1[0];
            String p2 = vetor1[1];
            //Dados vetor 2
            String p3 = vetor2[0];
            String p4 = vetor2[1];
            
          //String r1 = p1 + p3;
          //String r2 = p1 + p4;
          //String r3 = p2 + p3;
          //String r4 = p2 + p4;
          String resultado1 = "";
          String resultado2 = "";
            for (int i = 0; i < vetor2.length; i++) { 
                resultado1 += p1 + vetor2[i] + " " ;      
            }
            System.out.println(resultado1+" ");
            for (int j = 0; j < vetor2.length; j++) {
                resultado2 += p2 + vetor2[j] + " ";
            }
            System.out.println(resultado2+" ");
            jLResultado.setText("<html><table>\n" +
"                <thead>\n" +
"                    <tr>\n" +
"                        <th>X</th>\n" +
"                        <th>"+p3+"</th>\n" +
"                        <th>I"+p4+"</th>\n" +
"                    </tr>\n" +
"                </thead>\n" +
"\n" +
"                <tbody>\n" +
"                    <tr>\n" +
"                        <td><b>"+p1+"</b></td>\n" +
"                        <td>"+resultado1+"     "+"</td>\n" +
"                    </tr>\n" +
"                    <tr>\n" +
"                        <td><b>"+p2+"</b></td>\n" +
"                        <td>"+resultado2 +"    "+"</td>\n" +
"                    </tr>\n" +
"                </tbody>\n" +
"            </table></html>");
        }
        //Executara o cálculo se a segunda lei estiver marcada
        if(jRSegunda.isSelected()){
            
        }
    }//GEN-LAST:event_jBCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calcular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calcular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calcular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calcular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Calcular().setVisible(true);
                } catch (SQLException ex) {}
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBCalcular;
    private javax.swing.JButton jBSalvar;
    private javax.swing.JLabel jLResultado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRPrimeira;
    private javax.swing.JRadioButton jRSegunda;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTCampo1;
    private javax.swing.JTextField jTCampo2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
